### ISSUE TITLE
[Visual Recognition] System.IO.FileLoadException on WPF Project

### ISSUE THREAD

**Issue by Daiki-Kawanuma** [watson-developer-cloud/dotnet-standard-sdk#141]
System.IO.FileLoadException happen on WPF Project.

Project Environment:
- Visual Studio Community 2017 Version 15.1 (26403.3)
- .NET Framework 4.6
- IBM.WatsonDeveloperCloud.VisualRecognition.v3 ver1.2.0

Error Code:
System.IO.FileLoadException occurred
  HResult=0x8013141A
  Message=Could not load file or assembly 'System.Net.Http.Formatting, Version=5.2.4.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. Strong name validation failed. (Exception from HRESULT: 0x8013141A)
  Source=IBM.WatsonDeveloperCloud
  StackTrace:
   at IBM.WatsonDeveloperCloud.Http.WatsonHttpClient..ctor(String baseUri, String userName, String password)
   at IBM.WatsonDeveloperCloud.Service.WatsonService..ctor(String serviceName, String url)
   at IBM.WatsonDeveloperCloud.VisualRecognition.v3.VisualRecognitionService..ctor()
   at WatsonSdkWpfSample.MainWindow..ctor() in C:\Users\Daiki\documents\visual studio 2017\Projects\WatsonSdkWpfSample\WatsonSdkWpfSample\MainWindow.xaml.cs:line 34

Inner Exception 1:
SecurityException: Strong name validation failed. (Exception from HRESULT: 0x8013141A)

Is this bug or my project problem?

**Comment by atilatosta** [comment]
@Daiki-Kawanuma this is a bug! Related to this https://github.com/watson-developer-cloud/dotnet-standard-sdk/issues/118

**Comment by Daiki-Kawanuma** [comment]
Oh, I'm sorry. I didn't have enough checks.
If there is a problem, please close this issue.

**Comment by atilatosta** [comment]
@Daiki-Kawanuma no problem!

**Comment by Daiki-Kawanuma** [comment]
Nearly same problem also occured in ver 1.3.0
Do you have any help?

- Microsoft Visual Studio Community 2017 Version 15.5.1
- .NET Framework 4.7 WPF Project
- IBM.WatsonDeveloperCloud.VisualRecognition.v3 ver1.3.0

`Exception thrown: 'System.Security.VerificationException' in System.Net.Http.Formatting.dll
An exception of type 'System.Security.VerificationException' occurred in System.Net.Http.Formatting.dll but was not handled in user code
Method System.Net.Http.CloneableExtensions.Clone: type argument 'System.Net.Http.Headers.MediaTypeHeaderValue' violates the constraint of type parameter 'T'.`

**Comment by mediumTaj** [comment]
I believe @atilatosta is still looking into https://github.com/watson-developer-cloud/dotnet-standard-sdk/issues/118

**Comment by mediumTaj** [comment]
Is this still an issue?

**Comment by mediumTaj** [comment]
Closing due to inactivity. Please reopen if this is still an issue.
