### ISSUE TITLE
Update Text to Speech example

### ISSUE THREAD

**Issue by thiagoloureiro** [watson-developer-cloud/dotnet-standard-sdk#211]
Issue using the Latest source, and examples.

**(username and password working correctly with curl commands)**

For example
```
var obj = new TextToSpeechService(_username, _password);
var ret = obj.ListVoiceModels();
```
Error:

```
System.AggregateException: One or more errors occurred. (The API query failed with status code BadRequest: Bad Request) (The API query failed with status code BadRequest: Bad Request) ---> IBM.WatsonDeveloperCloud.Http.Exceptions.ServiceResponseException: The API query failed with status code BadRequest: Bad Request
   at IBM.WatsonDeveloperCloud.Http.Filters.ErrorFilter.OnResponse(IResponse response, HttpResponseMessage responseMessage) in C:\Projects\dotnet-standard-sdk\src\IBM.WatsonDeveloperCloud\Http\Filters\ErrorFilter.cs:line 53
   at IBM.WatsonDeveloperCloud.Http.Request.<GetResponse>d__30.MoveNext() in C:\Projects\dotnet-standard-sdk\src\IBM.WatsonDeveloperCloud\Http\Request.cs:line 203
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at IBM.WatsonDeveloperCloud.Http.Request.<AsMessage>d__23.MoveNext() in C:\Projects\dotnet-standard-sdk\src\IBM.WatsonDeveloperCloud\Http\Request.cs:line 139
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at IBM.WatsonDeveloperCloud.Http.Request.<As>d__24`1.MoveNext() in C:\Projects\dotnet-standard-sdk\src\IBM.WatsonDeveloperCloud\Http\Request.cs:line 144
   --- End of inner exception stack trace ---
   at IBM.WatsonDeveloperCloud.TextToSpeech.v1.TextToSpeechService.ListVoiceModels(String language, Dictionary`2 customData) in C:\Projects\dotnet-standard-sdk\src\IBM.WatsonDeveloperCloud.TextToSpeech.v1\TextToSpeechService.cs:line 410
   at testSpeech.Program.Main(String[] args) in C:\Projects\dotnet-standard-sdk\testSpeech\Program.cs:line 21
---> (Inner Exception #0) IBM.WatsonDeveloperCloud.Http.Exceptions.ServiceResponseException: The API query failed with status code BadRequest: Bad Request
   at IBM.WatsonDeveloperCloud.Http.Filters.ErrorFilter.OnResponse(IResponse response, HttpResponseMessage responseMessage) in C:\Projects\dotnet-standard-sdk\src\IBM.WatsonDeveloperCloud\Http\Filters\ErrorFilter.cs:line 53
   at IBM.WatsonDeveloperCloud.Http.Request.<GetResponse>d__30.MoveNext() in C:\Projects\dotnet-standard-sdk\src\IBM.WatsonDeveloperCloud\Http\Request.cs:line 203
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at IBM.WatsonDeveloperCloud.Http.Request.<AsMessage>d__23.MoveNext() in C:\Projects\dotnet-standard-sdk\src\IBM.WatsonDeveloperCloud\Http\Request.cs:line 139
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at IBM.WatsonDeveloperCloud.Http.Request.<As>d__24`1.MoveNext() in C:\Projects\dotnet-standard-sdk\src\IBM.WatsonDeveloperCloud\Http\Request.cs:line 144<---
```

This issue happen also with TexttoSpeech methods and so on.

**Comment by mediumTaj** [comment]
@thiagoloureiro I am able to list text to speech models.

```cs
TextToSpeechService tts = new TextToSpeechService("<username>", "<password>");
var models = tts.ListVoiceModels();

Console.WriteLine(string.Format("result: {0}", JsonConvert.SerializeObject(models, Formatting.Indented)));
Console.ReadKey();
```

Are there any specific methods that are not working? What region are you trying to access? You can set the URL to see if it helps
```
TextToSpeechService tts = new TextToSpeechService("<username>", "<password>");
tts.Endpoint = "<tts-service-endpoint>";
```
