### ISSUE TITLE
mono chokes on the new User-Agent 

### ISSUE THREAD

**Issue by main--** [watson-developer-cloud/dotnet-standard-sdk#335]
The more detailed `User-Agent` header introduced in #329 crashes in mono:

```
System.FormatException: Could not parse value for header 'User-Agent'
  at System.Net.Http.Headers.HttpHeaders.AddInternal (System.String name, System.Collections.Generic.IEnumerable`1[T] values, System.Net.Http.Headers.HeaderInfo headerInfo, System.Boolean ignoreInvalid) [0x0004e] in <bae862271f0b4964bff9e327d8b22444>:0 
  at System.Net.Http.Headers.HttpHeaders.Add (System.String name, System.Collections.Generic.IEnumerable`1[T] values) [0x00018] in <bae862271f0b4964bff9e327d8b22444>:0 
  at System.Net.Http.Headers.HttpHeaders.Add (System.String name, System.String value) [0x00000] in <bae862271f0b4964bff9e327d8b22444>:0 
  at IBM.WatsonDeveloperCloud.Http.HttpFactory.GetRequestMessage (System.Net.Http.HttpMethod method, System.Uri resource, System.Net.Http.Formatting.MediaTypeFormatterCollection formatters) [0x000eb] in <2329b907b3b742bfb11cfb4080def7b8>:0 
```

I realize that this went unnoticed because the library mainly targets .NET Core but given that it works just fine in mono except for this tiny problem I think it's worth fixing.

**Comment by mediumTaj** [comment]
would you like to put in a PR for this?

**Comment by main--** [comment]
So the trivial fix here would be to just remove the User-Agent header. But given that it was probably added for a reason (?) this is probably not appropriate? I don't know *exactly* why mono rejects this value, just that it's too complicated (maybe because of some special characters?) - I stopped diving into the parsing code once it started instantiating lexers...

**Comment by mediumTaj** [comment]
Yeah we need the user agent for analytics. Is it possible that mono is erroring on giving some of the info we need for user-agent?
https://github.com/watson-developer-cloud/dotnet-standard-sdk/blob/a035159aa5cf1a7218284cfcbcbd52e995d3f6f0/src/IBM.WatsonDeveloperCloud/Http/HttpFactory.cs#L52

**Comment by main--** [comment]
The string I'm getting is `<SDK_VERSION> Unix 5.0.0.1 Mono5.18.0(makepkg/5266e6a8f10WedJan2301:37:40CET2019)`. After some trial and error it seems that both the parentheses as well as the colons make it crash. So running (something like) `String.Join("", System.Runtime.InteropServices.RuntimeInformation.FrameworkDescription.Split(new char[] { ' ', '(', ')', ':' }))` instead of just removing spaces should do the trick (doesn't crash for me).

**Comment by mediumTaj** [comment]
Can you post what the value of the user-agent is after this change?

**Comment by main--** [comment]
It would be exactly the same, just without any parentheses or colons: `<SDK_VERSION> Unix 5.0.0.1 Mono5.18.0makepkg/5266e6a8f10WedJan23013740CET2019`

**Comment by mediumTaj** [comment]
in HttpFactory.cs I'm looking to change the method to remove parentheses, colons and semicolons. Will this work for mono? I'll have to find a better way to do this when I start working on the major release. 
```
public static HttpRequestMessage GetRequestMessage(HttpMethod method, Uri resource, MediaTypeFormatterCollection formatters)
{
    HttpRequestMessage request = new HttpRequestMessage(method, resource);

    // add default headers
    request.Headers.Add("accept", formatters.SelectMany(p => p.SupportedMediaTypes).Select(p => p.MediaType));
    string osInfo = System.Runtime.InteropServices.RuntimeInformation.OSDescription;
    int versionIndex = osInfo.IndexOfAny("0123456789".ToCharArray());
    string os = osInfo.Substring(0, versionIndex).Replace(" ", "").Replace("(", "").Replace(")", "").Replace(":", "").Replace(";", "");
    string osVersion = osInfo.Substring(versionIndex).Replace(" ", "").Replace("(", "").Replace(")", "").Replace(":", "").Replace(";", "");
    request.Headers.Add("User-Agent", 
        string.Format(
            "{0} {1} {2} {3}", 
            Constants.SDK_VERSION, 
            os,
            osVersion,
            System.Runtime.InteropServices.RuntimeInformation.FrameworkDescription.Replace(" ", "")
        ));

    return request;
}
```

**Comment by main--** [comment]
No. The problem is the `FrameworkDescription` and the code you just posted doesn‘t fix that. So either apply the replacements individually to the **framework description** or the way I gave you or just replace *after formatting* to fix up the entire string (to make it more robust/futureproof).

**Comment by tehmantra** [comment]
Also getting this problem on macos after upgrading.

`<PackageReference Include="IBM.WatsonDeveloperCloud.Assistant.v1" Version="2.16.0" />`

```
System.FormatException: The format of value '18.2.0DarwinKernelVersion18.2.0:ThuDec2020:46:53PST2018;root:xnu-4903.241.1~1/RELEASE_X86_64 .NETCore4.6.27414.05' is invalid.
   at System.Net.Http.Headers.HttpHeaderParser.ParseValue(String value, Object storeValue, Int32& index)
   at System.Net.Http.Headers.HttpHeaders.ParseAndAddValue(HeaderDescriptor descriptor, HeaderStoreItemInfo info, String value)
   at System.Net.Http.Headers.HttpHeaders.Add(HeaderDescriptor descriptor, String value)
   at IBM.WatsonDeveloperCloud.Http.HttpFactory.GetRequestMessage(HttpMethod method, Uri resource, MediaTypeFormatterCollection formatters)
   at IBM.WatsonDeveloperCloud.Http.WatsonHttpClient.SendAsync(HttpMethod method, String resource)
   at IBM.WatsonDeveloperCloud.Assistant.v1.AssistantService.Message(String workspaceId, MessageRequest request, Nullable`1 nodesVisitedDetails, Dictionary`2 customData)
   at Shook.Api.Services.WatsonService.SendMessage(String text, ConversationContext context) in /Users/michael/Projects/shook/shook-api/Services/WatsonService.cs:line 41
```

**Comment by mediumTaj** [comment]
@tehmantra @main-- Can you give me what you get for the value of
```
System.Runtime.InteropServices.RuntimeInformation.OSDescription
```

**Comment by main--** [comment]
On mono (from archlinux repo):

* `RuntimeInformation.OSDescription`: "Unix 5.0.5.1"
* `RuntimeInformation.FrameworkDescription`: "Mono 5.18.1 (makepkg/9cb3348c311 Thu Mar 21 17:20:20 UTC 2019)"

**Comment by mediumTaj** [comment]
Can you see if this PR fixes the user-agent parsing issue?
https://github.com/watson-developer-cloud/dotnet-standard-sdk/pull/344

**Comment by main--** [comment]
Appears to be fixed, no crash here.
