### ISSUE TITLE
Natural Language Understanding.. The api query failed with status UNAUTHORIZED

### ISSUE THREAD

**Issue by njjbailey** [watson-developer-cloud/dotnet-standard-sdk#353]
Hi there,

We have come across an unexpected authorization issue when using Natural Language Understanding with .net CORE 2.2:

Error:

System.AggregateException
  HResult=0x80131500
  Message=One or more errors occurred. (The API query failed with status code Unauthorized: Unauthorized | x-global-transaction-id:  | X-DP-Watson-Tran-ID:  | error: {"code":401, "error": "Unauthorized"}) (The API query failed with status code Unauthorized: Unauthorized | x-global-transaction-id:  | X-DP-Watson-Tran-ID:  | error: {"code":401, "error": "Unauthorized"})
  Source=IBM.WatsonDeveloperCloud.NaturalLanguageUnderstanding.v1
  StackTrace:
   at IBM.WatsonDeveloperCloud.NaturalLanguageUnderstanding.v1.NaturalLanguageUnderstandingService.Analyze(Parameters parameters, Dictionary`2 customData)
   at SearchDemoCore.Program.AnalyseText(String text) in C:\Users\Nick\source\repos\SearchDemoCore\SearchDemoCore\Program.cs:line 125
   at SearchDemoCore.Program.Main(String[] args) in C:\Users\Nick\source\repos\SearchDemoCore\SearchDemoCore\Program.cs:line 91

Inner Exception 1:
ServiceResponseException: The API query failed with status code Unauthorized: Unauthorized | x-global-transaction-id:  | X-DP-Watson-Tran-ID:  | error: {"code":401, "error": "Unauthorized"}

Steps to reproduce:

1) Provision a Natural Language Understanding service
2) Set up a new API key for the service
3) Call the service using the following code:

`private static AnalysisResults AnalyseText(string text)
        {
            var _naturalLanguageUnderstandingService = new IBM.WatsonDeveloperCloud.NaturalLanguageUnderstanding.v1.NaturalLanguageUnderstandingService();

            _naturalLanguageUnderstandingService.VersionDate = "2018-11-16";

            _naturalLanguageUnderstandingService.ApiKey = _apiKeyWatson;

            _naturalLanguageUnderstandingService.SetEndpoint("https://gatewaylon.watsonplatform.net/natural-language-understanding/api");

            Parameters parameters = new Parameters()
            {
                Text = text,
                Features = new Features()
                {
                    Keywords = new KeywordsOptions()
                    {
                        Limit = 8,
                        Sentiment = true,
                        Emotion = true
                    }
                }
            };`

.NET version used is: .NET Core 2.2

Are we perhaps not ordering the setting of variables correctly? We've tried a few combinations but nothing seems to work.

Thanks for your help, Nick

**Comment by njjbailey** [comment]
Solved my own issue.. apologies.. here is the answer:

Use tokens:

`TokenOptions iamAssistantTokenOptions = new TokenOptions()
            {
                IamApiKey = _apiKeyWatson,
                ServiceUrl = _watsonUrl
            };

            var _naturalLanguageUnderstandingService = new IBM.WatsonDeveloperCloud.NaturalLanguageUnderstanding.v1.NaturalLanguageUnderstandingService(iamAssistantTokenOptions, _watsonVersion);`
