### ISSUE TITLE
[testing] Speech to Text integration test failing

### ISSUE THREAD

**Issue by mediumTaj** [watson-developer-cloud/dotnet-standard-sdk#57]
DeleteSession_Success is failing with the following error

```
Test Name:	DeleteSession_Success
Test FullName:	IBM.WatsonDeveloperCloud.SpeechToText.IntegrationTests.SpeechToTextServiceIntegrationTest.DeleteSession_Success
Test Source:	C:\Users\asant\Documents\_projects\dotnet-standard-sdk\test\IBM.WatsonDeveloperCloud.SpeechToText.IntegrationTests\SpeechToTextServiceIntegrationTest.cs : line 93
Test Outcome:	Failed
Test Duration:	0:00:00.3238356

Result StackTrace:	
at IBM.WatsonDeveloperCloud.Http.Filters.ErrorFilter.OnResponse(IResponse response, HttpResponseMessage responseMessage) in C:\Users\asant\Documents\_projects\dotnet-standard-sdk\src\IBM.WatsonDeveloperCloud\Http\Filters\ErrorFilter.cs:line 39
   at IBM.WatsonDeveloperCloud.Http.Request.<GetResponse>d__23.MoveNext() in C:\Users\asant\Documents\_projects\dotnet-standard-sdk\src\IBM.WatsonDeveloperCloud\Http\Request.cs:line 146
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at IBM.WatsonDeveloperCloud.Http.Request.<AsMessage>d__17.MoveNext() in C:\Users\asant\Documents\_projects\dotnet-standard-sdk\src\IBM.WatsonDeveloperCloud\Http\Request.cs:line 106
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at IBM.WatsonDeveloperCloud.Http.Request.<As>d__18`1.MoveNext() in C:\Users\asant\Documents\_projects\dotnet-standard-sdk\src\IBM.WatsonDeveloperCloud\Http\Request.cs:line 111
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at IBM.WatsonDeveloperCloud.SpeechToText.v1.SpeechToTextService.GetModel(String modelName) in C:\Users\asant\Documents\_projects\dotnet-standard-sdk\src\IBM.WatsonDeveloperCloud.SpeechToText\v1\SpeechToTextService.cs:line 94
   at IBM.WatsonDeveloperCloud.SpeechToText.IntegrationTests.SpeechToTextServiceIntegrationTest.DeleteSession_Success() in C:\Users\asant\Documents\_projects\dotnet-standard-sdk\test\IBM.WatsonDeveloperCloud.SpeechToText.IntegrationTests\SpeechToTextServiceIntegrationTest.cs:line 101
Result Message:	
Test method IBM.WatsonDeveloperCloud.SpeechToText.IntegrationTests.SpeechToTextServiceIntegrationTest.DeleteSession_Success threw exception: 
IBM.WatsonDeveloperCloud.Http.Exceptions.ServiceResponseException: The API query failed with status code 429: Too Many Requests


```

**Comment by mediumTaj** [comment]
This is because we are using watson-api-explorer endpoint. We need to use the real service endpoint with working credentials for integration tests.

**Comment by AmenehSh** [comment]
j
