### ISSUE TITLE
[testing] Language Translator integration test failing

### ISSUE THREAD

**Issue by mediumTaj** [watson-developer-cloud/dotnet-standard-sdk#58]
GetModelDetails is failing with the following error
```
Test Name:	GetModelDetails
Test FullName:	IBM.WatsonDeveloperCloud.LanguageTranslator.IntegrationTests.LanguageTranslatorServiceIntegrationTest.GetModelDetails
Test Source:	C:\Users\asant\Documents\_projects\dotnet-standard-sdk\test\IBM.WatsonDeveloperCloud.LanguageTranslator.IntegrationTests\LanguageTranslatorServiceIntegrationTest.cs : line 81
Test Outcome:	Failed
Test Duration:	0:00:00.3149318

Result StackTrace:	
at IBM.WatsonDeveloperCloud.Http.Filters.ErrorFilter.OnResponse(IResponse response, HttpResponseMessage responseMessage) in C:\Users\asant\Documents\_projects\dotnet-standard-sdk\src\IBM.WatsonDeveloperCloud\Http\Filters\ErrorFilter.cs:line 39
   at IBM.WatsonDeveloperCloud.Http.Request.<GetResponse>d__23.MoveNext() in C:\Users\asant\Documents\_projects\dotnet-standard-sdk\src\IBM.WatsonDeveloperCloud\Http\Request.cs:line 146
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at IBM.WatsonDeveloperCloud.Http.Request.<AsMessage>d__17.MoveNext() in C:\Users\asant\Documents\_projects\dotnet-standard-sdk\src\IBM.WatsonDeveloperCloud\Http\Request.cs:line 106
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at IBM.WatsonDeveloperCloud.Http.Request.<As>d__18`1.MoveNext() in C:\Users\asant\Documents\_projects\dotnet-standard-sdk\src\IBM.WatsonDeveloperCloud\Http\Request.cs:line 111
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at IBM.WatsonDeveloperCloud.LanguageTranslator.v2.LanguageTranslatorService.GetModelDetails(String modelId) in C:\Users\asant\Documents\_projects\dotnet-standard-sdk\src\IBM.WatsonDeveloperCloud.LanguageTranslator\v2\LanguageTranslatorService.cs:line 169
   at IBM.WatsonDeveloperCloud.LanguageTranslator.IntegrationTests.LanguageTranslatorServiceIntegrationTest.GetModelDetails() in C:\Users\asant\Documents\_projects\dotnet-standard-sdk\test\IBM.WatsonDeveloperCloud.LanguageTranslator.IntegrationTests\LanguageTranslatorServiceIntegrationTest.cs:line 86
Result Message:	
Test method IBM.WatsonDeveloperCloud.LanguageTranslator.IntegrationTests.LanguageTranslatorServiceIntegrationTest.GetModelDetails threw exception: 
IBM.WatsonDeveloperCloud.Http.Exceptions.ServiceResponseException: The API query failed with status code 429: Too Many Requests
```

**Comment by mediumTaj** [comment]
This is because we are using watson-api-explorer endpoint. We need to use the real service endpoint with working credentials for integration tests.
